# Generated by Django 6.0 on 2025-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('roll', models.IntegerField()),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('fathers_name', models.CharField(max_length=266)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CIVIL', 'Civil'), ('MECH', 'Mechanical')], default='CSE', max_length=10)),
                ('course', models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('DIPLOMA', 'Diploma'), ('CERT', 'Certificate')], default='BSc', max_length=11)),
                ('student_photo', models.ImageField(upload_to='images/')),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
