# Generated by Django 6.0 on 2025-12-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=150)),
                ('group_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('board_university', models.CharField(blank=True, max_length=150, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='a_accounts.register')),
            ],
        ),
    ]
