# Generated by Django 6.0 on 2025-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_accounts', '0002_academicqualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicqualification',
            old_name='gpa',
            new_name='cgpa_gpa',
        ),
    ]
