# Generated by Django 6.0 on 2025-12-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_accounts', '0003_rename_gpa_academicqualification_cgpa_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicqualification',
            old_name='cgpa_gpa',
            new_name='gpa',
        ),
    ]
